{% set name = "libcf" %}
{% set version = "1.0.3" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libcf/archive/1.0.3.tar.gz
  sha256: bf8102f55489fe96cd98e365e0e013837396c84a8c47c8a4eb15ef627817c1c9

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libnetcdf
    - libblas
    - libcblas
    - curl >=7.44.0,<8
    - libuuid
  run:
    - python
    - libnetcdf
    - curl >=7.44.0,<8
    - libuuid
    - libblas
    - libcblas
test:
  imports:
    - pycf
    - pycf.libCFConfig

about:
  home: http://www.unidata.ucar.edu/software/libcf/
  license: 'UCAR/UNIDATA'
  license_file: 'COPYRIGHT'
  summary: 'LibCF library access data files in accordance with the CF Conventions.'
  description: |
    By using libcf, a data producer can produce files that conform to the CF
    standards, without having to write netCDF code to create and decode all
    the attributes that the CF convention uses to store meta-data. A data consumer
    can use libcf to read any file which conforms to the CF conventions; the
    file does not need to be created with libcf to be read by libcf
  dev_url: https://sourceforge.net/projects/libcf/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - xylar
    - downiec
    - muryanto1
