travis:
  secure:
    BINSTAR_TOKEN: iQnDYxOIMLioTZGJHbaQyVlmdJJraWNNaFGV7f80TVt6TpJ//Gz0hku6E88Un5lA/qvvDHfnLanKCmrdwkxGhuVc2nCY4afH2Fh4ZRhM15xzIPuQJ8vg1/nZ8pSu5LAmWoTqYbV6PUIaxDORqoRZI3QBB/DCioYCGRSuvB8rkJb6IiQAt9ntGbs2sH2GfyyQrKfkRgP9XKZDqCgHm6LJR2JybjcIwIhLz5oy2+D3JJYPWIlV/8rTQ44VdrugKeXh4vNpDEGG1vO8l6A5cYeScsAOyEOCYThWqWGlUDILfJodTdYuzMYJtAtzvIi3FDCS52O+Jo5Ek3Fla5KXqevE5jV/Rm/TLfV0BBnmBplj7LT3TzNbv6Jfwhfk1KYffQ9Ejc+X9j7B3UbA8ndYOQgWLXnNm5kMj8dcN41Pzq9P/MYVEGfbTLfJLzJVwDuj0jn1E22KH2jY2PvHOM9HS+ke77qRrYGMUoB8cRMRxx+IsTOvH2/1UrcJ5ZE0NXQGMU9OHUhiqEPc2iidVK9mEj6EWonFgVjEbbiWjXW5bxQ4kXtbdjESq2k6El4GC7l++rWRRwdwrbFXycPoqh3hl5So1HwtPZxp+WsnYpQAqo438PnbVLp19VfcD42KNs136946jdJAnrJyE3C24OFSkfkErCIIVv9r+XsmDHc7cqVvNE8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
